### ISSUE TITLE
插件本地下载后，Vscode无法安装

### ISSUE THREAD

**Issue by yhhwpp** [Maroon1/px2rem#3]
插件本地下载后，Vscode无法安装，提示“文件将不再编辑器中显示，因为它是二进制文件、非常大或使用不支持的文本编码”。

**Comment by maroon1** [comment]
<img width="628" alt="2017-03-07 19 08 22" src="https://cloud.githubusercontent.com/assets/15511355/23653977/92361770-0369-11e7-8046-be5a3cd525f3.png">
vscode更改的了本地文件的安装方式，可以按照截图中的命令安装本地vsix文件

**Comment by yhhwpp** [comment]
ok，Thanks
