### ISSUE TITLE
本地安装之后没有效果啊 

### ISSUE THREAD

**Issue by hipi** [Maroon1/px2rem#4]

**Comment by hipi** [comment]
![image](https://cloud.githubusercontent.com/assets/22478003/25740678/1b28d2f6-31ba-11e7-8652-ae081a6b148b.png)
![image](https://cloud.githubusercontent.com/assets/22478003/25740698/2d2bbd92-31ba-11e7-982f-8ddc60e47277.png)
这是我的插件和设置 是冲突吗

**Comment by maroon1** [comment]
直接在控制面板输入px2rem有效果吗？

**Comment by maroon1** [comment]
有可能是快捷键冲突了

**Comment by hipi** [comment]
面板输入px2rem有提示![image](https://cloud.githubusercontent.com/assets/22478003/25741763/df0fb17c-31be-11e7-8b1a-a75ea6ce47cd.png)

**Comment by hipi** [comment]
看到了 快捷键变成```alt```+```c```

**Comment by maroon1** [comment]
插件可以使用了吗，我这边测试是可以正常使用的

**Comment by hipi** [comment]
用可以用只是快捷键变成```alt+c```
